name: Spotless Code Formatter

on:
  pull_request: # Run on every pull request
    branches:
      - [ "**" ] # Match all branches
  push:         # Optionally run on direct push
    branches:
      - [ "**" ] # Match all branches

jobs:
  spotless-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # Use OpenJDK
          java-version: '21'     # Adjust depending on your project

      - name: Run Spotless Check
        run: |
          ./gradlew spotlessCheck
      - name: Apply Spotless Changes 🧹 (optional)
        if: ${{ github.event_name == 'push' }} # Run only on push (optionally enforce formatting)
        run: |
          ./gradlew spotlessApply